name: Build C++ app
on:
  pull_request:
    paths: cpp/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest
      # Setup vcpkg: ensures vcpkg is downloaded and built.
      # Since vcpkg.json is being used later on to install the packages
      # when `run-cmake` runs, no packages are installed at this time
      # (and vcpkg does not run).
      - name: Setup new (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: fc349a7b35348173d4d24621ae04ad80e2375957

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: cpp/CMakeLists.txt
          # This is the name of the CMakePresets.json's configuration to use to generate
          # the project files. This configuration leverages the vcpkg.cmake toolchain file to
          # run vcpkg and install all dependencies specified in vcpkg.json.
          configurePreset: vcpkg
          # This is the name of the CMakePresets.json's configuration to build the project.
          buildPreset: vcpkg
          testPreset: vcpkg
